parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - lead_time 
  - arrival_year
  - arrival_month
  - arrival_date
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type

columns_to_drop:
  - Booking_ID
target: booking_status
catalog_name: marvelous_mlops
schema_name: pre_processed
experiment_name_basic: /Users/akmukherjee@gmail.com/my-random-forest-experiment
pipeline_id: pipeline-0123abcd
