parameters:
  learning_rate: 0.01
  max_depth: 15
  random_state: 42
  n_estimators: 250
  subsample: 0.8
  colsample_bytree: 0.8
  
num_features:
  - lead_time 
  - arrival_year
  - arrival_month
  - arrival_date
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type


target: booking_status
catalog_name: marvelous_mlops
schema_name: pre_processed
experiment_name_basic: /Users/akmukherjee@gmail.com/my-random-forest-experiment
experiment_name_fe: /Users/akmukherjee@gmail.com/my-random-forest-fe-experiment
pipeline_id: pipeline-0123abcd
